import { Category, Product } from "./types";

export type CategoryDef = { id: Category; label: string };

export const categories: CategoryDef[] = [
  { id: "Copos", label: "Copos" },
  { id: "Barcas", label: "Barcas" },
  { id: "Potes", label: "Potes" },
  { id: "Roletas", label: "Roletas" },
];

export const products: Product[] = [
  {
    id: "copo-300",
    nome: "Açaí 300ml Cremoso",
    descricao: "Açaí cremoso e encorpado de 300ml com 2 acompanhamentos à sua escolha",
    preco: 10.0,
    precoMix: 11.0,
    imagem: "/copo_sem_cobertura.png",
    categoria: "Copos",
  },
  {
    id: "copo-400",
    nome: "Açaí 400ml Cremoso",
    descricao: "Açaí cremoso de 400ml com 3 acompanhamentos à sua escolha",
    preco: 13.0,
    precoMix: 14.0,
    imagem: "/copo_com_banana.jpg",
    categoria: "Copos",
  },
  {
    id: "copo-500",
    nome: "Açaí 500ml Cremoso — O Mais Pedido",
    descricao: "O tamanho mais pedido: 500ml de açaí cremoso com 3 acompanhamentos à sua escolha",
    preco: 15.0,
    precoMix: 16.0,
    imagem: "/copo_com_banana.jpg",
    categoria: "Copos",
  },
  {
    id: "copo-700",
    nome: "Açaí 700ml Cremoso — Pra Dividir",
    descricao: "Açaí cremoso e encorpado de 700ml com 3 acompanhamentos à sua escolha",
    preco: 22.0,
    precoMix: 23.0,
    imagem: "/copo.png",
    categoria: "Copos",
  },
  {
    id: "barca-pequena",
    nome: "Barca P",
    descricao: "3 acompanhamentos, 1 fruta e 1 calda",
    preco: 26.0,
    precoMix: 28.0,
    imagem: "/barcadeacai.png",
    categoria: "Barcas",
  },
  {
    id: "barca-media",
    nome: "Barca M",
    descricao: "4 acompanhamentos, 2 frutas e 1 calda",
    preco: 34.2,
    precoMix: 37.0,
    imagem: "/barcadeacai.png",
    categoria: "Barcas",
  },
  {
    id: "barca-grande",
    nome: "Barca G",
    descricao: "5 acompanhamentos, 3 frutas e 1 calda",
    preco: 58.0,
    precoMix: 60.0,
    imagem: "/barcadeacai.png",
    categoria: "Barcas",
  },
  {
    id: "pote-350",
    nome: "Pote Love — 350ml",
    descricao: "2 acompanhamentos e 1 calda",
    preco: 14.0,
    precoMix: 16.0,
    imagem: "/pote.jpg",
    categoria: "Potes",
  },
  {
    id: "pote-550",
    nome: "Pote M — 550ml",
    descricao: "3 acompanhamentos, 1 fruta e 1 calda",
    preco: 16.0,
    precoMix: 18.0,
    imagem: "/pote.jpg",
    categoria: "Potes",
  },
  {
    id: "pote-1litro",
    nome: "Pote G — 1 Litro",
    descricao: "3 acompanhamentos, 1 fruta e 1 calda",
    preco: 36.0,
    precoMix: 39.0,
    imagem: "/pote.jpg",
    categoria: "Potes",
  },
  {
    id: "roleta-pequena",
    nome: "Roleta P",
    descricao: "3 acompanhamentos, 1 fruta e 1 calda",
    preco: 22.0,
    precoMix: 23.0,
    imagem: "/roleta_acai.png",
    categoria: "Roletas",
  },
  {
    id: "roleta-media",
    nome: "Roleta M",
    descricao: "3 acompanhamentos, 2 frutas e 1 calda",
    preco: 26.0,
    precoMix: 27.0,
    imagem: "/roleta_acai.png",
    categoria: "Roletas",
  },
  {
    id: "roleta-grande",
    nome: "Roleta G",
    descricao: "3 acompanhamentos, 2 frutas e 1 calda",
    preco: 35.0,
    precoMix: 36.0,
    imagem: "/roleta_acai.png",
    categoria: "Roletas",
  },
];
